# A service call that returns suitable grasping poses
# 

am_msgs/Object object
am_msgs/TargetZone target_zone
geometry_msgs/Pose target_pose


---
# An error message. An empty string indicates success.
string error_message
float64 object_mass
geometry_msgs/Pose[] object_grip_pose
geometry_msgs/Pose[] object_safe_pose
geometry_msgs/Pose[] object_vision_pose
uint16[] object_skip_vision
uint16[] grip_pose_type
float64[] object_grasp_width
geometry_msgs/Pose[] target_place_pose
geometry_msgs/Pose[] target_safe_pose
geometry_msgs/Pose[] target_vision_pose
uint16[] target_skip_vision
uint16[] place_pose_type
geometry_msgs/Pose[] push_safe_pose
geometry_msgs/Pose[] push_target_pose
geometry_msgs/Vector3[] object_grip_r_tcp_com