# A service call that returns a suitable grasping pose
# 

am_msgs/Object object
# geometry_msgs/Pose abs_pose


---
# An error message. An empty string indicates success.
string error_message
geometry_msgs/Pose grasp_pose
float64 grasp_width
float64 object_height
