#goal definition
geometry_msgs/Pose goal_pose
euroc_c2_msgs/Configuration goal_config
int32 planning_algorithm
int32 speed_percentage
int32 inter_steps
string planning_frame
float64 allowed_time
time stamp

---
#result definition
geometry_msgs/Pose reached_pose
bool reached_goal
int32 error_reason
---
#feedback
float64 execution_time
float64 estimated_motion_time

