#goal definition
am_msgs/Object object
am_msgs/TargetZone target_zone
am_msgs/Sensor[] sensors
uint16 mode
---
#result definition
geometry_msgs/Pose abs_object_pose
bool object_detected
time stamp
---
#feedback definition
float64 execution_time
float64 uncertainty