controller_list:
  - name: Arm_controller
    joints:
      - lwr_joint_1
      - lwr_joint_2
      - lwr_joint_3
      - lwr_joint_4
      - lwr_joint_5
      - lwr_joint_6
      - lwr_joint_7
  - name: LinearTisch_controller
    joints:
      - LinearTisch
  - name: Gripper_controller
    joints:
      - lwr_joint_before_finger1
      - lwr_joint_before_finger2
  - name: All_controller
    joints:
      - LinearTisch
      - lwr_joint_1
      - lwr_joint_2
      - lwr_joint_3
      - lwr_joint_4
      - lwr_joint_5
      - lwr_joint_6
      - lwr_joint_7
      - lwr_joint_before_finger1
      - lwr_joint_before_finger2
  - name: LinearTischArm_controller
    joints:
      - LinearTisch
      - lwr_joint_1
      - lwr_joint_2
      - lwr_joint_3
      - lwr_joint_4
      - lwr_joint_5
      - lwr_joint_6
      - lwr_joint_7
