# Requests the timing of a given path of configurations. The service interpolates a
# trajectory according to the specified acceleration and velocity limits and returns
# the expected arrival time at each configuration (via point) in the path.

# The names of the joints used in the movement. Defines a mapping for the other arrays.
string[] joint_names
# The start pose of the path.
Configuration start_pose
# The path in configurations.
Configuration[] path
# The joint velocity and acceleration limits which are required for the interpolation.
Limits[] joint_limits
# The cartesian velocity and acceleration limits at the tool center point. Set to zero to ignore.
CartesianLimits tcp_limits
---
# An error message. Empty string indicates success.
string error_message
# The time at each via point in the specified path.
time[] time_at_via_point