# The MoveAlongJointPath service moves the system joints along a path 
# of configurations. The service interpolates the path according to the
# specified velocity and acceleration limits and then starts to execute
# the resulting trajectory at the specified start time.

# The names of the used joints in the movement. Defines a mapping for the other arrays.
string[] joint_names
# The path in configurations.
Configuration[] path
# The simulation time point at which to start the movement (or zero to start as soon as possible).
time start_sim_time
# The joint velocity and acceleration limits which are required for the trajectory interpolation.
Limits[] joint_limits
# The optional cartesian velocity and acceleration limits at the tool center point. Set to zero to ignore.
CartesianLimits tcp_limits
---
# An error message. An empty string indicates success.
string error_message
# Indicates the stop reason. Possible stop reasons:
# - Movement finished at goal: string contains "path finished".
# - Movement stopped due to user defined stop condition: string contains "stop_condition <index>" where index is the position in the SetStopConditions conditions[] array.
# - An error occured: Human readable error string.
string stop_reason