# Sets the sensor update divisor of the specified camera. A lower sensor update rate increases the simulation performance.

# The sensor name to set the update divisor. The sensor names are specified in the scene description.
string sensor_name
# The divisor to control the frame rate of the camera. The resulting framerate will be the camera rate from the description / update_divisor.
uint8 update_divisor

---
# An error message. Empty string indicates success.
string error_message