# Starts the simulator with the specified task.

# The user id of the challenger.
string user_id
# The desired task / scene, selected from the list of scenes returned by the ListScenes service.
string scene_name
---
# An error message: Empty string indicates succes.
string error_message
# The description of the selected task in yaml format.
string description_yaml