joint_limits:
  lwr_joint_4:
    has_velocity_limits: true
    max_velocity: 2.7925
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_3:
    has_velocity_limits: true
    max_velocity: 2.7925
    has_acceleration_limits: false
    max_acceleration: 0
  joint_before_finger2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_1:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_7:
    has_velocity_limits: true
    max_velocity: 3.6652
    has_acceleration_limits: false
    max_acceleration: 0
  axis_x:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_5:
    has_velocity_limits: true
    max_velocity: 4.7124
    has_acceleration_limits: false
    max_acceleration: 0
  joint_before_finger1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_2:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_joint_6:
    has_velocity_limits: true
    max_velocity: 3.6652
    has_acceleration_limits: false
    max_acceleration: 0
  axis_y:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0