planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  ESTkConfigDefault:
    type: geometric::EST
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    projection_evaluator: joints(lwr_joint_1,lwr_joint_7)
    longest_valid_segment_fraction: 0.001 #was 0.01
  LBKPIECEkConfigDefault_2DOF:
    type: geometric::LBKPIECE
    projection_evaluator: joints(axis_x,axis_y)
    longest_valid_segment_fraction: 0.001
  LBKPIECEkConfigDefault_7DOF:
    type: geometric::LBKPIECE
    projection_evaluator: joints(lwr_joint_1,lwr_joint_7)
    longest_valid_segment_fraction: 0.001 #was 0.01
  LBKPIECEkConfigDefault_9DOF:
    type: geometric::LBKPIECE
    projection_evaluator: joints(axis_x,lwr_joint_7)
    longest_valid_segment_fraction: 0.001 #was 0.01
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  RRTstarkConfigDefault:
    type: geometric::RRTstar
  TRRTkConfigDefault:
    type: geometric::TRRT
  PRMkConfigDefault:
    type: geometric::PRM
  PRMstarkConfigDefault:
    type: geometric::PRMstar
LWR_9DOF:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault_9DOF
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(axis_x,lwr_joint_7)
  longest_valid_segment_fraction: 0.001 #was 0.01
LWR_7DOF:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault_7DOF
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(lwr_joint_1,lwr_joint_7)
  longest_valid_segment_fraction: 0.001 #was 0.01
LWR_2DOF:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault_2DOF
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(axis_x,axis_y)
  longest_valid_segment_fraction: 0.01
gripper:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
